### PR TITLE
[#6] Configured time before expiration alert appears

### PR DESCRIPTION
**Pull request by rdlabspl**
- Now time when expiration warning will appear is configured. It's the biggest value from settings.PLANS_EXPIRATION_REMIND or 14.
piggyback:
- removed deprecated functions and configurations from demo urls and settings

### CODE REVIEW

**Comment by sebastian-code** [comment]
This is great @rdlabspl we appreciate it a lot. Please, apply your PR to the develop branch, so we can include additional work, keeping better control over the releases.

**Comment by rdlabspl** [comment]
But `PLANS_EXPIRATION_REMIND ` is listed in your settings configuration as iterable: https://django-plans-swapps.readthedocs.io/en/latest/settings.html#plans-expiration-remind.

We can leave it as it is or create new variable for this purpose which will be int.

**Comment by cdvv7788** [comment]
@rdlabspl I completely missed that bit of documentation, sorry. Confused both variables. I will merge it.

**Comment by sebastian-code** [comment]
Merged manually to develop branch

**Pull request merged**
